### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Sprinter1999** [anranLi515/FL-sample-selection-baseline#1]
Hey Anran, are you from the team of Xiangyang Li and Lan Zhang? I'm Xuefen from ICT-CAS, and personally I'm very interested in your published papers, such as Sample-level selection in FL and FLDebugger, I just wonder why your team decide not to opensource these good works to make it more impactful?

**Comment by anranLi515** [comment]
Hi Xuefen, you are right. We are applying for software copyrights for these source codes, and we will publish them soon.

**Comment by Sprinter1999** [comment]
Great, I'm looking forward to that : ). I'm watching for the codes for infocom '21 paper (sample-level selection in FL) for a year.
